<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_Field</name>
   <tag></tag>
   <elementGuidId>a91d1ac0-ab41-4b0e-9c71-b19ded19e785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ff_3_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ff_3_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fb95fa0-cc0a-4d9b-bcc6-1c84cc16993e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>dffcae47-5be7-4bd9-a1d3-a3d180a838f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4cd83880-a8ed-42d8-8d82-2bfb608d3994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ff_3_email</value>
      <webElementGuid>26247ce2-7c67-4cf6-ba51-9d6877133742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-el-form-control</value>
      <webElementGuid>28487573-b7d7-4855-b19a-28bef8a5a03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>johndoe@fluentforms.com</value>
      <webElementGuid>185d7aef-65d4-4adc-aaf5-5dc5e8deb384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>db32c801-b158-44cf-aad5-55e5d44dfa18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23e64d1e-dc22-41fb-92aa-33bc873a96d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>041e0835-4ecb-4957-a294-b33550a29afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ff_3_email&quot;)</value>
      <webElementGuid>727ae68b-bc86-4288-8263-b03df5246cb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ff_3_email']</value>
      <webElementGuid>5f380305-812c-4bb6-8d5b-9b9717b2d3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_3']/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>6d723d0d-d2e1-41c1-bd59-c417c2cb7a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>4075cc67-c705-4998-a4e2-a172f14ad3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'ff_3_email' and @placeholder = 'johndoe@fluentforms.com']</value>
      <webElementGuid>29bc6c57-3149-483a-a2e0-d84205099c64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
